default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: leon_development

test:
  <<: *default
  database: leon_test

production:
  <<: *default
  database: leon_production
  username: root
  password: root
